name: leatherjack
favicon: null
layout_spectrum: 0.56041
typography_spectrum: 0.44657
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#be522c'
    - '#2c2b26'
    - '#f3c38a'
    - '#818584'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
