name: leatherjack
favicon: null
layout_spectrum: 0.56041
typography_spectrum: 0.30804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6f4'
    - '#9a968a'
    - '#282b3e'
    - '#cacac8'
    - '#8e5424'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
