name: leatherjack
favicon: null
layout_spectrum: 0.56041
typography_spectrum: 0.44657
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#be522c'
    - '#2c2b26'
    - '#f3c38a'
    - '#818584'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
