name: leatherjack
favicon: null
layout_spectrum: 1
typography_spectrum: 0.05911
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8e704e'
    - '#735a3b'
    - '#a07e58'
    - '#5b472e'
    - '#b58e63'
  brandStrength: 0.5625
  lightness: 0.9047226379625499
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
